=== aigamo/primecloud-controller/auto-project/auto-api/WebContent/WEB-INF/auto-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
    jxb:version="2.1" jxb:extensionBindingPrefixes="xjc">
  <xs:annotation>
    <xs:appinfo>
      <jxb:globalBindings>
        <xjc:serializable uid="1"/>
      </jxb:globalBindings>
      <jxb:schemaBindings>
        <jxb:package name="jp.primecloud.auto.config.jaxb"/>
      </jxb:schemaBindings>
    </xs:appinfo>
  </xs:annotation>

  <xs:element name="autoConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="platforms"/>
        <xs:element ref="componentTypes"/>
        <xs:element ref="images"/>
        <xs:element ref="templates"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="platforms">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="platform" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="platform">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="no" type="xs:long"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="internal" type="xs:boolean"/>
        <xs:element name="aws" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="host" type="xs:string"/>
              <xs:element name="port" type="xs:int"/>
              <xs:element name="secure" type="xs:boolean"/>
              <xs:element name="euca" type="xs:boolean"/>
              <xs:element name="vpc" type="xs:boolean"/>
              <xs:element name="availabilityZone" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vmware" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="url" type="xs:string"/>
              <xs:element name="username" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
              <xs:element name="datacenter" type="xs:string"/>
              <xs:element name="publicNetwork" type="xs:string"/>
              <xs:element name="privateNetwork" type="xs:string"/>
              <xs:element name="computeResource" type="xs:string"/>
              <xs:element name="instanceTypes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="instanceType" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="cpu" type="xs:int"/>
                          <xs:element name="memory" type="xs:long"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="nifty" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="wsdl" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="cloudStack" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ipAddress" type="xs:string"/>
              <xs:element name="zoneId" type="xs:string"/>
              <xs:element name="networkid" type="xs:string"/>
              <xs:element name="domainid" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="proxy" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="host" type="xs:string"/>
              <xs:element name="port" type="xs:int"/>
              <xs:element name="user" type="xs:string" nillable="true"/>
              <xs:element name="password" type="xs:string" nillable="true"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="componentTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="componentType" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="componentType">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="no" type="xs:long"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="layer" type="xs:string"/>
        <xs:element name="runOrder" type="xs:int" nillable="true"/>
        <xs:element name="zabbixTemplate" type="xs:string" nillable="true"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="images">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="image" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="image">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="no" type="xs:long"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="platformNo" type="xs:long"/>
        <xs:element name="os" type="xs:string"/>
        <xs:element name="selectable" type="xs:boolean"/>
        <xs:element name="componentTypeNos" type="xs:string" nillable="true"/>
        <xs:element name="zabbixTemplate" type="xs:string" nillable="true"/>
        <xs:element name="aws" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="imageId" type="xs:string"/>
              <xs:element name="kernelId" type="xs:string" nillable="true"/>
              <xs:element name="ramdiskId" type="xs:string" nillable="true"/>
              <xs:element name="instanceTypes" type="xs:string"/>
              <xs:element name="ebsImage" type="xs:boolean"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vmware" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="templateName" type="xs:string"/>
              <xs:element name="instanceTypes" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="nifty" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="imageId" type="xs:string"/>
              <xs:element name="instanceTypes" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="cloudStack" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="templateId" type="xs:string"/>
              <xs:element name="zoneId" type="xs:string"/>
              <xs:element name="instanceTypes" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="templates">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="template" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="template">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="no" type="xs:long"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="components" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="component" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="componentTypeName" type="xs:string"/>
                    <xs:element name="comment" type="xs:string" nillable="true"/>
                    <xs:element name="diskSize" type="xs:int" nillable="true"/>
                    <xs:element name="associate" type="xs:string" nillable="true"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="instances" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="instance" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="platformName" type="xs:string"/>
                    <xs:element name="comment" type="xs:string" nillable="true"/>
                    <xs:element name="aws" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="imageName" type="xs:string"/>
                          <xs:element name="instanceType" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="vmware" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="imageName" type="xs:string"/>
                          <xs:element name="instanceType" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="nifty" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="imageName" type="xs:string"/>
                          <xs:element name="instanceType" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="cloudStack" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="imageName" type="xs:string"/>
                          <xs:element name="instanceType" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== aigamo/primecloud-controller/auto-project/auto-api/WebContent/WEB-INF/auto-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<autoConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="auto-config.xsd">
	<platforms>
		<platform>
			<no>4</no>
			<name>vmware</name>
			<internal>true</internal>
			<vmware>
				<url>https://172.22.77.15/sdk</url>
				<username>auto</username>
				<password>password</password>
				<datacenter>PaaS</datacenter>
				<publicNetwork>publicnw</publicNetwork>
				<privateNetwork>default</privateNetwork>
				<computeResource>Cluster1</computeResource>
				<instanceTypes>
					<instanceType>
						<name>small</name>
						<cpu>1</cpu>
						<memory>1024</memory>
					</instanceType>
					<instanceType>
						<name>medium</name>
						<cpu>2</cpu>
						<memory>2048</memory>
					</instanceType>
					<instanceType>
						<name>large</name>
						<cpu>4</cpu>
						<memory>4096</memory>
					</instanceType>
				</instanceTypes>
			</vmware>
		</platform>
		<platform>
			<no>1</no>
			<name>eucalyptus</name>
			<internal>true</internal>
			<aws>
				<host>172.22.0.21</host>
				<port>8773</port>
				<secure>false</secure>
				<euca>true</euca>
				<vpc>false</vpc>
				<availabilityZone>cluster01</availabilityZone>
			</aws>
		</platform>
		<platform>
			<no>2</no>
			<name>ec2</name>
			<internal>false</internal>
			<aws>
				<host>amazonaws.com</host>
				<port>443</port>
				<secure>true</secure>
				<euca>false</euca>
				<vpc>false</vpc>
			</aws>
		</platform>
		<platform>
			<no>3</no>
			<name>ec2_vpc</name>
			<internal>false</internal>
			<aws>
				<host>amazonaws.com</host>
				<port>443</port>
				<secure>true</secure>
				<euca>false</euca>
				<vpc>true</vpc>
			</aws>
		</platform>
		<platform>
			<no>5</no>
			<name>nifty</name>
			<internal>false</internal>
			<nifty>
				<wsdl>classpath:/NiftyCloud.wsdl</wsdl>
			</nifty>
		</platform>
        <platform>
            <no>6</no>
            <name>cloudstack</name>
            <internal>false</internal>
			<cloudStack>
				<host>amazonaws.com</host>
				<port>443</port>
				<secure>true</secure>
				<euca>false</euca>
				<vpc>true</vpc>
			</cloudStack>
        </platform>
	</platforms>

	<componentTypes>
		<componentType>
			<no>1</no>
			<name>mysql</name>
			<layer>db</layer>
			<runOrder>100</runOrder>
			<zabbixTemplate>Template_MW_MySQL</zabbixTemplate>
		</componentType>
		<componentType>
			<no>2</no>
			<name>tomcat</name>
			<layer>ap_java</layer>
			<runOrder>200</runOrder>
			<zabbixTemplate>Template_MW_Tomcat</zabbixTemplate>
		</componentType>
		<componentType>
			<no>3</no>
			<name>geronimo</name>
			<layer>ap_java</layer>
			<runOrder>200</runOrder>
			<zabbixTemplate>Template_MW_Geronimo</zabbixTemplate>
		</componentType>
		<componentType>
			<no>4</no>
			<name>apache</name>
			<layer>web</layer>
			<runOrder>300</runOrder>
			<zabbixTemplate>Template_MW_Apache</zabbixTemplate>
		</componentType>
		<componentType>
			<no>5</no>
			<name>ultramonkey</name>
			<layer>lb</layer>
			<runOrder>400</runOrder>
			<zabbixTemplate>Template_LB_UltraMonkey</zabbixTemplate>
		</componentType>
		<componentType>
			<no>6</no>
			<name>prjserver</name>
			<layer>prj</layer>
			<runOrder>1000</runOrder>
			<zabbixTemplate>Template_MW_Prjserver</zabbixTemplate>
		</componentType>
	</componentTypes>

	<images>
		<image>
			<no>1</no>
			<name>application</name>
			<platformNo>1</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- puppet38 -->
				<imageId>emi-10221144</imageId>
				<kernelId>eki-E51B17C3</kernelId>
				<ramdiskId>eri-46B5190F</ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,c1.xlarge</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>2</no>
			<name>application</name>
			<platformNo>2</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- puppet38 -->
				<imageId>ami-86d625ef</imageId>
				<kernelId>aki-54ce2c3d</kernelId>
				<ramdiskId>ari-56ce2c3f</ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>3</no>
			<name>application</name>
			<platformNo>3</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- puppet38 -->
				<imageId>ami-86d625ef</imageId>
				<kernelId>aki-54ce2c3d</kernelId>
				<ramdiskId>ari-56ce2c3f</ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>7</no>
			<name>ultramonkey</name>
			<platformNo>1</platformNo>
			<os>centos55</os>
			<selectable>false</selectable>
			<componentTypeNos>5</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- ultramonkey09 -->
				<imageId>emi-6AFC12FE</imageId>
				<kernelId>eki-BF111754</kernelId>
				<ramdiskId>eri-1F0618AA</ramdiskId>
				<instanceTypes>m1.small,c1.medium</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>8</no>
			<name>ultramonkey</name>
			<platformNo>2</platformNo>
			<os>centos55</os>
			<selectable>false</selectable>
			<componentTypeNos>5</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- ultramonkey09 -->
				<imageId>ami-0051a569</imageId>
				<kernelId>aki-94c527fd</kernelId>
				<ramdiskId>ari-96c527ff</ramdiskId>
				<instanceTypes>m1.small,c1.medium</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>9</no>
			<name>ultramonkey</name>
			<platformNo>3</platformNo>
			<os>centos55</os>
			<selectable>false</selectable>
			<componentTypeNos>5</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- ultramonkey09 -->
				<imageId>ami-0051a569</imageId>
				<kernelId>aki-94c527fd</kernelId>
				<ramdiskId>ari-96c527ff</ramdiskId>
				<instanceTypes>m1.small,c1.medium</instanceTypes>
				<ebsImage>false</ebsImage>
			</aws>
		</image>
		<image>
			<no>12</no>
			<name>application_ebs</name>
			<platformNo>2</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- puppet38 -->
				<imageId>ami-ead62583</imageId>
				<kernelId>aki-54ce2c3d</kernelId>
				<ramdiskId>ari-56ce2c3f</ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>true</ebsImage>
			</aws>
		</image>
		<image>
			<no>13</no>
			<name>application_ebs</name>
			<platformNo>3</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<aws>
				<!-- puppet38 -->
				<imageId>ami-ead62583</imageId>
				<kernelId>aki-54ce2c3d</kernelId>
				<ramdiskId>ari-56ce2c3f</ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>true</ebsImage>
			</aws>
		</image>
		<image>
			<no>21</no>
			<name>windows</name>
			<platformNo>2</platformNo>
			<os>windows2008R1</os>
			<selectable>true</selectable>
			<componentTypeNos></componentTypeNos>
			<zabbixTemplate></zabbixTemplate>
			<aws>
				<!-- Windows2008R2-JP-02 -->
				<imageId>ami-843fcced</imageId>
				<kernelId></kernelId>
				<ramdiskId></ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>true</ebsImage>
			</aws>
		</image>
		<image>
			<no>22</no>
			<name>windows</name>
			<platformNo>3</platformNo>
			<os>windows2008R1</os>
			<selectable>true</selectable>
			<componentTypeNos></componentTypeNos>
			<zabbixTemplate></zabbixTemplate>
			<aws>
				<!-- Windows2008R2-JP-02 -->
				<imageId>ami-843fcced</imageId>
				<kernelId></kernelId>
				<ramdiskId></ramdiskId>
				<instanceTypes>m1.large,m1.xlarge,m2.xlarge,m2.2xlarge,m2.4xlarge,c1.xlarge</instanceTypes>
				<ebsImage>true</ebsImage>
			</aws>
		</image>
		<image>
			<no>101</no>
			<name>application</name>
			<platformNo>4</platformNo>
			<os>centos55</os>
			<selectable>true</selectable>
			<componentTypeNos>1,2,3,4</componentTypeNos>.
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<vmware>
				<templateName>vm-template</templateName>
				<instanceTypes>small,medium,large</instanceTypes>
			</vmware>
		</image>
		<image>
			<no>103</no>
			<name>ultramonkey</name>
			<platformNo>4</platformNo>
			<os>centos55</os>
			<selectable>false</selectable>
			<componentTypeNos>5</componentTypeNos>
			<zabbixTemplate>Template_OS_Linux</zabbixTemplate>
			<vmware>
				<templateName>ultramonkey-template</templateName>
				<instanceTypes>small</instanceTypes>
			</vmware>
		</image>
		<image>
			<no>111</no>
			<name>windows</name>
			<platformNo>4</platformNo>
			<os>windows2008R2</os>
			<selectable>true</selectable>
			<componentTypeNos></componentTypeNos>
			<zabbixTemplate></zabbixTemplate>
			<vmware>
				<templateName>windows2008R2-template</templateName>
				<instanceTypes>small,medium,large</instanceTypes>
			</vmware>
		</image>
		<image>
			<no>201</no>
			<name>application</name>
			<platformNo>5</platformNo>
			<os>centos53</os>
			<selectable>true</selectable>
